version: "3.2"

services:

  backend:
    build: ./backend
    restart: always
    volumes:
      - ./Backend/:/var/www/html/
    container_name: "backend"
    ports:
      - "8000:80"
    depends_on:
      - database

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ecom
      MYSQL_ROOT_PASSWORD: sqlrootsql
    ports:
      - '3306:3306'
    expose:
      - '3306'

  frontend:
    build: ./frontend/
    container_name: frontend 
    volumes:
        - '/usr/src/app/node_modules'
        - './Frontend:/usr/src/app/'
    ports:
      - '4200:4200'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
